### ISSUE TITLE
Issues when moving bookmarks and folders

### ISSUE THREAD

**Issue by T-prog3** [toolbar-dial/toolbar-dial#37] opened 2022-09-05 01:20 UTC
1. When you move a `folder` one step left it then moves three steps left instead. When you move it right it moves two steps left.
2. When you move a `bookmark` one step on the first row it moves one step and then jumps back. If it doesn't jump back it jumps back if you left-click
  
3. When you move a `bookmark` one step on any other row it can jump up to 8 steps instead.

This behavior is a nightmare to maneuver

**Comment by lucaseverett** [comment] 2022-09-05 01:22
@T-prog3 What browser are you using, and what version of Toolbar Dial?

**Comment by T-prog3** [comment] 2022-09-05 01:28
I'm using Firefox and Toolbar Dial version 2.5

**Comment by lucaseverett** [comment] 2022-09-05 01:33
Have you tried closing and re-opening the browser? I'm unable to replicate the issue on any of my computers, so I think it's just a weird fluke with the update on your computer.

**Comment by T-prog3** [comment] 2022-09-05 01:44
Yes, i even tried my alternative Waterfox browser and it's the same issue there. But then i tried on a Firefox Nightly browser and there was no issue. But as soon as i imported all bookmarks the issues began.

**Comment by lucaseverett** [comment] 2022-09-05 01:47
What version of Firefox? I'm using 104.0.1.

**Comment by lucaseverett** [comment] 2022-09-05 01:51
I just installed Waterfox browser and can't reproduce the issue with my bookmarks. Will you please open the browser console (press F12 if using Windows) and let me know if there are any console errors when you move a bookmark?

**Comment by T-prog3** [comment] 2022-09-05 01:51
I have the same version 104.0.1. I also have about 200 bookmarks in 15 folders and some separator lines

**Comment by T-prog3** [comment] 2022-09-05 01:53
No error messages

**Comment by lucaseverett** [comment] 2022-09-05 01:58
Were you able to move bookmarks successfully prior to the 2.5 update? I don't have any separator lines in my bookmarks, but I'll add some and see if that causes the issue to happen for me.

**Comment by T-prog3** [comment] 2022-09-05 02:00
I never tried to move any bookmarks in Toolbar Dial before so i can't say

**Comment by lucaseverett** [comment] 2022-09-05 02:05
I added some separator lines in my bookmarks, and that causes the issue to happen for me as well. Thank you for letting me know about this issue. I haven't used Firefox in a while and had forgotten that it allowed separator lines. I'll work on a fix for this.

**Comment by T-prog3** [comment] 2022-09-05 03:10
Hm, I did the opposite and removed all my separator lines and it solved the issue with Bookmarks jumping 3 steps and 8 steps. But it still wants to go one extra step left each move so it may be another issue as well. This however seem to be occurring in the Bookmarks Menu only and not inside any folder.

**Comment by lucaseverett** [comment] 2022-09-05 04:01
Do you have any bookmarks that have a URL that start with javascript, place, about, chrome, edge, or file? E.g a bookmark to a file:// location?

Toolbar Dial filters out separators and bookmarks that can't be used as a link in a page, but when changing the sort order I don't take the position of those items into account. I understand the issue but will have to put some thought into how to handle it.

**Comment by lucaseverett** [comment] 2022-09-05 05:54
I believe I have a fix for this. Would you like to test it and make sure it works as expected?

**Comment by T-prog3** [comment] 2022-09-05 15:28
Great! Ye i can test it out to see if it solves the issue.

**Comment by lucaseverett** [comment] 2022-09-05 15:48
To install, go to about:debugging#/runtime/this-firefox and click the 'Load Temporary Add-on' button. Then select any file in the unzipped folder linked below.

[dist-firefox.zip](https://github.com/toolbar-dial/toolbar-dial/files/9491060/dist-firefox.zip)

**Comment by T-prog3** [comment] 2022-09-05 16:12
It solved the issue 100%. Well done!

**Comment by lucaseverett** [comment] 2022-09-05 17:50
Thank you for your help with reporting the issue and testing the fix! Version 2.5.1 has been released.

Fixed by 033dd6eff6213a6d1cbd66974b30c6b31ade4ebb.

**Closed by lucaseverett** 2022-09-05 17:50 UTC
